#!/bin/bash

# set -e ## error
set -x

git add .
git commit -m 'autocommit'
git push

ssh do2 "cd /mnt/volume_sfo2_01/projects/docker/volumes/demmitv_drupal_production_data/web/themes/demmitv_drupal_theme ; git pull && echo $HOSTNAME ok"

echo 'ok'
